### PR TITLE
Update nan

### PR DESCRIPTION
**Pull request by nicolashenry**
Fixes gh-27

### CODE REVIEW

**Comment by jhurliman** [comment]
+1 on this, would love to be able to use deasync with io.js 3.1.0.

**Comment by abbr** [comment]
hmm... tried your patch but still got following error on my osx:

```  
CXX(target) Release/obj.target/deasync/src/deasync.o
In file included from ../src/deasync.cc:1:
In file included from /Users/abbr/.node-gyp/3.1.0/include/node/uv.h:48:
/Users/abbr/.node-gyp/3.1.0/include/node/uv-errno.h:25:10: fatal error: 
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
```

**Comment by abbr** [comment]
Thanks for the pr. I confirmed this doesn't help solving issue #27. See my comments on that issue.

**Comment by abbr** [comment]
On double check, your patch works on my osx so I accepted it. The error I got was caused by Xcode.

**Comment by nicolashenry** [comment]
Thx :)

**Pull request merged**
